# Generated by Django 4.2.11 on 2025-09-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='distance',
        ),
    ]
